/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4pmrbwdarndhpn5udgklgl4uza.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pqhmm77aqzdsda25dalok5sw7a",
    "aws_cognito_identity_pool_id": "us-east-1:c7e1e1b9-6da3-4c53-a44c-5cb0a48529c4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PsV3obwoO",
    "aws_user_pools_web_client_id": "3do12nj0hoivfkohsocbh9siad",
    "oauth": {},
    "aws_user_files_s3_bucket": "v01sevenawarebe859b95023b4009ae1c155b07a5f728114508-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
