/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:07832cac-2744-48ed-83ed-d4d0a646d7e2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5GRQJroi5",
    "aws_user_pools_web_client_id": "5sbs6fl03l3qi1j7f0ltajvcnc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rqow53xb4zerdctfszrh3s5fc4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nk27gvazcnehlnj4tgkhvzoati"
};


export default awsmobile;
